### ISSUE TITLE
JsonRecord behaviour when json properties are missing

### ISSUE THREAD

**Issue by asherf** [hearsaycorp/normalize#42]
Currently, the behaviour is that when the a certain property is missing from the json data and we try to access that property on an instance of a JsonRecord we get an AttributeError.
A default value can be specified, but it must be of the same type of the property and cannot be None.

**Comment by asherf** [comment]
@samv can we move forward with this issue?

**Comment by samv** [comment]
This deficiency has been addressed by the 0.7.0 release.
