### ISSUE TITLE
Normalize should have some type of base exception type?

### ISSUE THREAD

**Issue by rogerhu** [hearsaycorp/normalize#61]
Right now catching all normalize exceptions require a blanket try...except...this seems to cause us to mask a lot of potential issues.

Do you have any opinions about modifying https://github.com/hearsaycorp/normalize/blob/master/normalize/exc.py#L27 to inherit from a common NormalizeException type?

**Comment by rbm** [comment]
:+1:

**Comment by tulioz** [comment]
Merged #62
